import datetime

DEFAULT_FILTER_SELECTION = '일반 필터'
DEFAULT_START_DATE = datetime.date(2017, 4, 20)
DEFAULT_START_TIME = datetime.time(7, 0, 0)
DEFAULT_END_DATE = datetime.date(2022, 12, 31)
DEFAULT_END_TIME = datetime.time(23, 0, 0)
DEFAULT_SELECTED_LINES = ['전체']
DEFAULT_SELECTED_STATIONS = ['전체']
DEFAULT_ON_OFF = '전체'
DEFAULT_CHATBOT_FILTER_INPUT = ''
DEFAULT_CHATBOT_FILTER_OUTPUT = ''
